services:
  gatus:
    image: docker.io/twinproduction/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    container_name: gatus
    user: "999:999"
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - "8080:8080"
    restart: always
