services:
  lan-orangutan:
    image: docker.io/291group/lan-orangutan:3.3.8@sha256:86b55c80eeb13df264b44da866975083f80530966984d01de323849a1dbe8496
    container_name: lan-orangutan
    network_mode: host
    restart: always
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
    environment:
      - ORANGUTAN_PORT=291
      - TZ=America/Toronto
      - "ORANGUTAN_PASSWORD={{ lan_orangutan_password }}"
      - "ORANGUTAN_NETWORKS={{ homelab_lan_subnet }}"
    volumes:
      - ./data:/var/lib/lan-orangutan
