services:
  miniflux:
    image: docker.io/miniflux/miniflux:2.3.1@sha256:42f14382a035e9d9bbc33910ca53f72d47177f75c3c638d2c5a85adf5582d538
    container_name: miniflux
    networks:
      - miniflux
    depends_on:
      - miniflux-db
    restart: always
    environment:
      - DATABASE_URL=postgres://{{ miniflux_db_user }}:{{ miniflux_db_password }}@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME={{ miniflux_admin_username }}
      - ADMIN_PASSWORD={{ miniflux_admin_password }}
      - BASE_URL={{ miniflux_base_url }}
  miniflux-db:
    image: docker.io/postgres:18.4@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    container_name: miniflux-db
    networks:
      - miniflux
    environment:
      - POSTGRES_USER={{ miniflux_db_user }}
      - POSTGRES_PASSWORD={{ miniflux_db_password }}
    volumes:
      - miniflux-db:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
  newt:
    image: docker.io/fosrl/newt:1.13.0@sha256:63d956c8fdee889255e441ec405193b47b1fd2d975b505492ec848a8007f4fc3
    container_name: newt-miniflux
    restart: unless-stopped
    networks:
      - miniflux
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ miniflux_newt_id }}
      - NEWT_SECRET={{ miniflux_newt_secret }}
volumes:
  miniflux-db:
    name: miniflux-db
networks:
  miniflux:
    name: miniflux
