
services:
  miniflux:
    image: docker.io/miniflux/miniflux:2.3.0@sha256:65266db84761d09d999946218adfc91fd7abbd4a1086f74b3ad0e51083e30df2
    container_name: miniflux
    networks:
      - miniflux
    depends_on:
      - miniflux-db
    restart: always
    environment:
      - DATABASE_URL=postgres://{{ miniflux_db_user }}:{{ miniflux_db_password }}@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME={{ miniflux_admin_username }}
      - ADMIN_PASSWORD={{ miniflux_admin_password }}
      - BASE_URL=https://miniflux.snake-cloud.ts.net
  miniflux-db:
    image: docker.io/postgres:18.4@sha256:775a0820dd34e907ec63277e388d145056d427548e461d7953a070edb5de3a3a
    container_name: miniflux-db
    networks:
      - miniflux
    environment:
      - POSTGRES_USER={{ miniflux_db_user }}
      - POSTGRES_PASSWORD={{ miniflux_db_password }}
    volumes:
      - miniflux-db:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
  newt:
    image: docker.io/fosrl/newt:1.12.5@sha256:3c009663332145cae39b940b07857469038d5e9d71aacb1497e78795ba4e3b9b
    container_name: newt-miniflux
    restart: unless-stopped
    networks:
      - miniflux
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ miniflux_newt_id }}
      - NEWT_SECRET={{ miniflux_newt_secret }}
volumes:
  miniflux-db:
    name: miniflux-db
networks:
  miniflux:
    name: miniflux
