services:
  miniflux:
    image: docker.io/miniflux/miniflux:2.3.2@sha256:cd353a6af9ce663291f405eddef26fa0d567f486b521c5d34e3fb50e41938b9a
    container_name: miniflux
    networks:
      - miniflux
    depends_on:
      - miniflux-db
    restart: always
    environment:
      - DATABASE_URL=postgres://{{ miniflux_db_user }}:{{ miniflux_db_password }}@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME={{ miniflux_admin_username }}
      - ADMIN_PASSWORD={{ miniflux_admin_password }}
      - BASE_URL={{ miniflux_base_url }}
  miniflux-db:
    image: docker.io/postgres:18.4@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    container_name: miniflux-db
    networks:
      - miniflux
    environment:
      - POSTGRES_USER={{ miniflux_db_user }}
      - POSTGRES_PASSWORD={{ miniflux_db_password }}
    volumes:
      - miniflux-db:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
  newt:
    image: docker.io/fosrl/newt:1.15.0@sha256:d69d047c816ca7721eae90d5f3cd3be53b615b3d498678be21488d666538ee5c
    container_name: newt-miniflux
    restart: unless-stopped
    networks:
      - miniflux
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ miniflux_newt_id }}
      - NEWT_SECRET={{ miniflux_newt_secret }}
volumes:
  miniflux-db:
    name: miniflux-db
networks:
  miniflux:
    name: miniflux
