services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.35@sha256:2d6fb6cd50c1327f7c802b9471c173b4d6e509111022ed550c8690b2451c5709
    container_name: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=America/Toronto
      - BASE_URL={{ zerobyte_base_url }}
      - APP_SECRET={{ zerobyte_app_secret }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - /mnt:/mnt:ro
      - ~/.config/rclone:/root/.config/rclone:ro
