services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:5.3.4@sha256:f7edc52fe03f5d424182b06faa72962c625f5e78ff3c9e8457e9617f20d0e611
    container_name: upsnap
    network_mode: host
    restart: always
    cap_add:
      - NET_RAW
    cap_drop:
      - ALL
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=America/Toronto
