services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:5.6.0@sha256:2bda1e8638d97269ddeacf9b9d60b14557c3b6685e1d1facf496dfc0df4a8a92
    container_name: upsnap
    network_mode: host
    restart: always
    cap_add:
      - NET_RAW
    cap_drop:
      - ALL
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=America/Toronto
