services:
  overseerr:
    image: sctx/overseerr:1.33.2
    container_name: overseerr
    network_mode: host
    environment:
      - LOG_LEVEL=debug
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ./overseerr/config:/app/config
    restart: unless-stopped
