services:
  igotify:
    container_name: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:v1.6.0.1@sha256:69fc3469e8461284f5b7794bad3466cead0030cc7e2e182239125360a6befd9d
    restart: always
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - igotify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/Version"]
      interval: "3s"
      timeout: "3s"
      retries: 5
    volumes:
      - ~/api-data:/app/data
    environment:
      GOTIFY_URLS: "{{ gotify_url }}"
      GOTIFY_CLIENT_TOKENS: "{{ igotify_gotify_client_tokens }}"
  newt:
    image: docker.io/fosrl/newt:1.16.0@sha256:345fdeb369be6608d82c41d70637636c78b2c04a6112ff6ec20fc21c48afc899
    container_name: newt-igotify
    restart: unless-stopped
    networks:
      - igotify
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ igotify_newt_id }}
      - NEWT_SECRET={{ igotify_newt_secret }}

networks:
  igotify:
    name: igotify
