services:
  invidious:
    # https://quay.io/repository/invidious/invidious?tab=tags
    image: quay.io/invidious/invidious:2026.08.12-fc3c75e@sha256:5feefaabd835e4acdbda84f1fbddb7f286cfd3ac90e9d45159e4b7a6e1ea5303
    container_name: invidious
    restart: always
    networks:
      - invidious
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: "{{ invidious_db_user }}"
          password: "{{ invidious_db_password }}"
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
          - private_url: "http://companion:8282/companion"
        invidious_companion_key: "{{ invidious_companion_secret_key }}"
        hmac_key: "{{ invidious_hmac_key }}"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db

  companion:
    # https://quay.io/repository/invidious/invidious-companion?tab=tags
    image: quay.io/invidious/invidious-companion:2026.08.10-0b9b9ea@sha256:8ef815960c75f56d52c3ff07dc1e99a68a797a0ef1e89874e9ea8cd3c3c1dceb
    container_name: invidious-companion
    environment:
      - SERVER_SECRET_KEY={{ invidious_companion_secret_key }}
    restart: unless-stopped
    networks:
      - invidious
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - ./companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/postgres:18.4@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    container_name: invidious-db
    restart: always
    networks:
      - invidious
    volumes:
      - ./postgresdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: "{{ invidious_db_user }}"
      POSTGRES_PASSWORD: "{{ invidious_db_password }}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  newt:
    image: docker.io/fosrl/newt:1.16.0@sha256:345fdeb369be6608d82c41d70637636c78b2c04a6112ff6ec20fc21c48afc899
    container_name: newt-invidious
    restart: unless-stopped
    networks:
      - invidious
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ invidious_newt_id }}
      - NEWT_SECRET={{ invidious_newt_secret }}
networks:
  invidious:
    name: invidious
