services:
  tunarr:
    container_name: tunarr
    image: docker.io/chrisbenincasa/tunarr:1.2.21@sha256:51b3e80dc9d3cb1e86f6a0258bb63703801508b1fe63562217245a9594cc295e
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8000:8000
    environment:
      - TZ=America/New_York
      - TUNARR_SERVER_TRUST_PROXY=true
    volumes:
      - ./tunarr-data:/config/tunarr
