services:
  tunarr:
    container_name: tunarr
    image: docker.io/chrisbenincasa/tunarr:1.2.11@sha256:b836037815521f6c6ba18a7edc97ab6dbc51de5815ec4750edddec047c646a5d
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8000:8000
    environment:
      - TZ=America/New_York
      - TUNARR_SERVER_TRUST_PROXY=true
    volumes:
      - ./tunarr-data:/config/tunarr
