services:
  tunarr:
    container_name: tunarr
    image: docker.io/chrisbenincasa/tunarr:1.3.11@sha256:f4faefbbf0c3d6872e542135d766f590955a8dbba3019c93219b96cc6becd3dc
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8000:8000
    mem_limit: 4g
    memswap_limit: 4g
    environment:
      - TZ=America/New_York
      - TUNARR_SERVER_TRUST_PROXY=true
    volumes:
      - ./tunarr-data:/config/tunarr
