services:
  bedrock:
    image: docker.io/itzg/minecraft-bedrock-server:2026.4.2@sha256:f2334f7a0bd35b2b5f10993cdb74b8c76c27f0806ddda8bdbe5b953ecb63334b
    container_name: bedrock
    environment:
      EULA: "TRUE"
      LEVEL_NAME: "Bedrock level"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: always
