services:
  bedrock:
    image: docker.io/itzg/minecraft-bedrock-server:2026.7.3@sha256:45c8f292b289659c0be469b2eaaebfc1fbfefdf5c060a0df5ed53fe9e2e7c563
    container_name: bedrock
    environment:
      EULA: "TRUE"
      LEVEL_NAME: "Bedrock level"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: always
