services:
  bedrock:
    image: itzg/minecraft-bedrock-server:2025.9.0
    container_name: bedrock
    environment:
      EULA: "TRUE"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: always
