services:
  bedrock:
    image: docker.io/itzg/minecraft-bedrock-server:2026.4.3@sha256:3c2523ea7bd931b8b7a9fc6bb333fdd75984e74808614d581796ff9c3a3e0def
    container_name: bedrock
    environment:
      EULA: "TRUE"
      LEVEL_NAME: "Bedrock level"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: always
