services:
  lidarr:
    container_name: lidarr
    image: docker.io/linuxserver/lidarr:3.1.0@sha256:ca2f95634d422fdeccfbff2a42cbe3a4fed1170f7e3546d99d5d5f2c9c9aa03b
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/lidarr/config:/config
      - /mnt:/mnt
      - /music:/music
    restart: always
