services:
  lidarr:
    container_name: lidarr
    image: docker.io/linuxserver/lidarr:3.1.0@sha256:60be9a1faad3dfba5a711163fc18526845e2ce7b50b463dd9effae7f766c9beb
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/lidarr/config:/config
      - /mnt:/mnt
      - /music:/music
    restart: always
