services:
  lidarr:
    container_name: lidarr
    image: docker.io/linuxserver/lidarr:3.1.0@sha256:67887807b13ae025c0fe979da298347c8609969087ab064c81d8e9acc1e06bbf
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/lidarr/config:/config
      - /mnt:/mnt
      - /music:/music
    restart: always
