services:
  gotify:
    image: docker.io/gotify/server:3.0.0@sha256:d75e89e0e28389c00c2556afe01282a37ee9756b0285799aa25214243aebd5e5
    container_name: gotify
    networks:
      - gotify
    restart: always
    volumes:
      - ~/data:/app/data
    security_opt:
      - no-new-privileges:true
  newt:
    image: docker.io/fosrl/newt:1.14.0@sha256:60c78391e3b5cb8a260490fb26b8b7329ed5448077629da89a564af80d3a9fad
    container_name: newt-gotify
    restart: unless-stopped
    networks:
      - gotify
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ gotify_newt_id }}
      - NEWT_SECRET={{ gotify_newt_secret }}
networks:
  gotify:
    name: gotify
