services:
  gotify:
    image: docker.io/gotify/server:3.1.1@sha256:44fc5bbd1c0618878e33073d38c2c13126b48f245c3fe12236b1da48eb203b86
    container_name: gotify
    networks:
      - gotify
    restart: always
    volumes:
      - ~/data:/app/data
    security_opt:
      - no-new-privileges:true
  newt:
    image: docker.io/fosrl/newt:1.16.0@sha256:345fdeb369be6608d82c41d70637636c78b2c04a6112ff6ec20fc21c48afc899
    container_name: newt-gotify
    restart: unless-stopped
    networks:
      - gotify
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ gotify_newt_id }}
      - NEWT_SECRET={{ gotify_newt_secret }}
networks:
  gotify:
    name: gotify
