services:
  adguard-home:
    image: docker.io/adguard/adguardhome:v0.107.77@sha256:a8e81f370e086a9fa8c8a9f36dfe0222a8b1439541a4f39bc90aa360fce54cab
    container_name: adguard-home
    network_mode: host
    restart: always
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
