services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.32.2
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
