services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.31.2
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  traefik:
    image: traefik:v3.3.3
    container_name: traefik-prowlarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/data/traefik.yaml:/traefik.yaml:ro
      - ./traefik/data/dynamic.yaml:/dynamic.yaml:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
