services:
  searxng:
    container_name: searxng
    # https://hub.docker.com/r/searxng/searxng/tags
    image: docker.io/searxng/searxng:2026.7.3-747cec4c2@sha256:b7492e1b8fcb376191809982e6a45dc809a5d0e641d81feaa53a1fac6c599b9e
    restart: always
    networks:
      - searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:9@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  newt:
    image: docker.io/fosrl/newt:1.14.0@sha256:60c78391e3b5cb8a260490fb26b8b7329ed5448077629da89a564af80d3a9fad
    container_name: newt-searxng
    restart: unless-stopped
    networks:
      - searxng
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ searxng_newt_id }}
      - NEWT_SECRET={{ searxng_newt_secret }}

volumes:
  valkey-data2:
networks:
  searxng:
    name: searxng
