services:
  searxng:
    container_name: searxng
    # https://hub.docker.com/r/searxng/searxng/tags
    image: docker.io/searxng/searxng:2026.9.23-dcf1d477a@sha256:205e303efc8b3fd024ba67f43376e16212a4a21a561de008f22ae07411e9d3ab
    restart: always
    networks:
      - searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:9@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  newt:
    image: docker.io/fosrl/newt:1.17.0@sha256:3465d85200cceb0f46dad8e63a40b69ec043a81df66ed0c514714302e9b83dde
    container_name: newt-searxng
    restart: unless-stopped
    networks:
      - searxng
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ searxng_newt_id }}
      - NEWT_SECRET={{ searxng_newt_secret }}

volumes:
  valkey-data2:
networks:
  searxng:
    name: searxng
