services:
  sonarr:
    container_name: sonarr
    # https://hub.docker.com/r/linuxserver/sonarr/tags
    image: docker.io/linuxserver/sonarr:4.0.19@sha256:24acea2956a0ccb11f103877d9f4f8576600fb34bff34820ed749c2256dab89f
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/sonarr/config:/config
      - /mnt:/mnt
