services:
  sonarr:
    container_name: sonarr
    # https://hub.docker.com/r/linuxserver/sonarr/tags
    image: docker.io/linuxserver/sonarr:4.0.17@sha256:e6c9a091735fede0c2a205c69e7d4c2f0188eaf2bec7e42d8a26c017e5f2a910
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/sonarr/config:/config
      - "/mnt/media/TV Shows:/mnt/media/TV Shows"
      - /mnt/media/Torrents:/downloads
