services:
  maloja:
    image: docker.io/krateng/maloja:3.2.6@sha256:1ccc7f4f78256242ada110efffe255617c974714455199c59a1fb0696ab23734
    container_name: maloja
    restart: always
    ports:
      - "42010:42010"
    volumes:
      - "$PWD/data:/data"
    environment:
      - MALOJA_SKIP_SETUP=true
      - MALOJA_FORCE_PASSWORD=stub
      - MALOJA_DATA_DIRECTORY=/data
