services:
  maloja:
    image: docker.io/krateng/maloja:3.2.5@sha256:6013039eab0a1c8a0edbc7df7aeb9c9449ccb55186d9efa3bf16704957dbe7ff
    container_name: maloja
    restart: always
    ports:
      - "42010:42010"
    volumes:
      - "$PWD/data:/data"
    environment:
      - MALOJA_SKIP_SETUP=true
      - MALOJA_FORCE_PASSWORD=stub
      - MALOJA_DATA_DIRECTORY=/data
