services:
  maloja:
    image: krateng/maloja:3.2.4
    container_name: maloja
    ports:
    - "42010:42010"
    volumes:
    - "$PWD/data:/data"
    environment:
      - MALOJA_SKIP_SETUP=true
      - MALOJA_FORCE_PASSWORD=stub
      - MALOJA_DATA_DIRECTORY=/data
