---
- name: Install immich
  hosts: immich
  tasks:
    - ansible.builtin.include_tasks:
        file: ../../tasks/install-docker-on-ubuntu.yml

    - ansible.builtin.include_tasks:
        file: ../../tasks/install-common-dependencies.yml

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: "~/docker-compose.yml"
        mode: "0640"

    - name: Copy .env
      ansible.builtin.template:
        src: .env
        dest: "~/.env"
        mode: "0640"

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny

    - name: Pull and start containers
      community.docker.docker_compose_v2:
        project_src: .
        pull: always

    - name: Prune docker images
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: false
        networks: false
        volumes: false
        builder_cache: false
