services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=homepage.snake-cloud.ts.net
      - "HOMEPAGE_VAR_GOTIFY_API_KEY={{ homepage_gotify_api_key }}"
      - "HOMEPAGE_VAR_IMMICH_API_KEY={{ homepage_immich_api_key }}"
      - "HOMEPAGE_VAR_ADGUARD_HOME_USERNAME={{ homepage_adguard_home_username }}"
      - "HOMEPAGE_VAR_ADGUARD_HOME_PASSWORD={{ homepage_adguard_home_password }}"
      - "HOMEPAGE_VAR_TRUENAS_API_KEY={{ homepage_truenas_api_key }}"
      - "HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY={{ homepage_openweathermap_api_key }}"
      - "HOMEPAGE_VAR_GATUS_URL={{ gatus_url }}"
      - "HOMEPAGE_VAR_SPEEDTEST_TRACKER_URL={{ speedtest_tracker_url }}"
      - "HOMEPAGE_VAR_JELLYFIN_URL={{ jellyfin_url }}"
      - "HOMEPAGE_VAR_GOTIFY_URL={{ gotify_server_url }}"
      - "HOMEPAGE_VAR_IMMICH_URL={{ immich_url }}"
      - "HOMEPAGE_VAR_ADGUARD_HOME_URL={{ adguard_home_url }}"
      - "HOMEPAGE_VAR_TRUENAS_URL={{ truenas_url }}"
      - "HOMEPAGE_VAR_PROXMOX_URL={{ proxmox_url }}"
      - "HOMEPAGE_VAR_OPNSENSE_URL={{ opnsense_url }}"
      - "HOMEPAGE_VAR_HOMEASSISTANT_URL={{ homeassistant_url }}"
      - "HOMEPAGE_VAR_AUDIOBOOKSHELF_URL={{ audiobookshelf_url }}"
      - "HOMEPAGE_VAR_MALOJA_URL={{ maloja_url }}"
      - "HOMEPAGE_VAR_FORGEJO_URL={{ forgejo_url }}"
      - "HOMEPAGE_VAR_NAVIDROME_URL={{ navidrome_url }}"
      - "HOMEPAGE_VAR_INVIDIOUS_URL={{ invidious_url }}"
      - "HOMEPAGE_VAR_CHANGEDETECTION_URL={{ changedetection_url }}"
      - "HOMEPAGE_VAR_BENTOPDF_URL={{ bentopdf_url }}"
      - "HOMEPAGE_VAR_ARCHIVEBOX_URL={{ archivebox_url }}"
      - "HOMEPAGE_VAR_LUBELOGGER_URL={{ lubelogger_url }}"
      - "HOMEPAGE_VAR_GRAFANA_URL={{ grafana_url }}"
      - "HOMEPAGE_VAR_WATCHYOURLAN_URL={{ watchyourlan_url }}"
      - "HOMEPAGE_VAR_BESZEL_URL={{ beszel_url }}"
      - "HOMEPAGE_VAR_PROWLARR_URL={{ prowlarr_url }}"
      - "HOMEPAGE_VAR_UMAMI_URL={{ umami_url }}"
      - "HOMEPAGE_VAR_ROMM_URL={{ romm_url }}"
      - "HOMEPAGE_VAR_MINIFLUX_URL={{ miniflux_url }}"
      - "HOMEPAGE_VAR_SONARR_URL={{ sonarr_url }}"
      - "HOMEPAGE_VAR_RADARR_URL={{ radarr_url }}"
      - "HOMEPAGE_VAR_LIDARR_URL={{ lidarr_url }}"
      - "HOMEPAGE_VAR_DISPATCHARR_URL={{ dispatcharr_url }}"
      - "HOMEPAGE_VAR_QBITTORRENT_URL={{ qbittorrent_url }}"
      - "HOMEPAGE_VAR_SEERR_URL={{ seerr_url }}"
      - "HOMEPAGE_VAR_PAPERLESS_NGX_URL={{ paperless_ngx_url }}"
      - "HOMEPAGE_VAR_UPSNAP_URL={{ upsnap_url }}"
      - "HOMEPAGE_VAR_GL_MT3000_URL={{ gl_mt3000_url }}"
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./config/icons:/app/public/icons
    restart: always
