services:
  traefik:
    image: traefik:v3.1.1
    container_name: traefik-homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ./traefik/data/traefik.yaml:/traefik.yaml:ro
      - ./traefik/data/dynamic.yaml:/dynamic.yaml:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.5
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/images
      - ./config/icons:/app/public/icons
    restart: unless-stopped
