services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.4
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: homepage.snake-cloud.ts.net
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/images
      - ./config/icons:/app/public/icons
    restart: unless-stopped
