services:
  stirling-pdf:
    image: frooodle/s-pdf:1.2.0
    container_name: stirling-pdf
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - ./configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
