services:
  stirling-pdf:
    image: frooodle/s-pdf:0.43.1
    container_name: stirling-pdf
    network_mode: service:ts-stirling-pdf
    restart: unless-stopped
    volumes:
      - ./trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - ./configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
  ts-stirling-pdf:
    image: tailscale/tailscale:v1.80
    container_name: ts-stirling-pdf
    hostname: stirling-pdf
    environment:
      - TS_AUTHKEY={{ stirling_pdf_ts_authkey }}
      - TS_SERVE_CONFIG=/config/stirling-pdf.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
volumes:
  ts-stirling-pdf:
    driver: local
