services:
  qui:
    image: ghcr.io/autobrr/qui:v1.17.0@sha256:fb3832e68f66b056e1b049d16c40732661e7b73999bc642d4b11469a3ebbabd3
    container_name: qui
    restart: unless-stopped
    ports:
      - "7476:7476"
    volumes:
      - ./qui:/config
