services:
  qui:
    image: ghcr.io/autobrr/qui:v1.15.0@sha256:da33f8c850f7d6f1bfaee26b9553b21411e872639d54193906fa2cec51af1d0f
    container_name: qui
    restart: unless-stopped
    ports:
      - "7476:7476"
    volumes:
      - ./qui:/config
