services:
  archivebox:
    image: docker.io/archivebox/archivebox:0.9.70@sha256:8c21bb233130d86963e2ffab143264dfb8908c966a12a00f2180bb88e6f6305a
    container_name: archivebox
    command: server --quick-init 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    environment:
      - MEDIA_MAX_SIZE=750m
      - ALLOWED_HOSTS=archivebox.snake-cloud.ts.net
      - CSRF_TRUSTED_ORIGINS=https://archivebox.snake-cloud.ts.net
    volumes:
      - ./data:/data
