services:
  archivebox:
    image: docker.io/archivebox/archivebox:0.9.71@sha256:56057dbe5ab387441e96c25a531d8934768bc977f94b9a91428f6913945e9b0d
    container_name: archivebox
    command: server --quick-init 0.0.0.0:8000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--show-error", "--max-time", "5", "http://127.0.0.1:8000/health/"]
      interval: 30s
      timeout: 20s
      retries: 15
    ports:
      - 8000:8000
    environment:
      - MEDIA_MAX_SIZE=750m
      - ALLOWED_HOSTS=archivebox.snake-cloud.ts.net
      - CSRF_TRUSTED_ORIGINS=https://archivebox.snake-cloud.ts.net
    volumes:
      - ./data:/data
