services:
  wyze-bridge:
    container_name: wyze-bridge
    ports:
      - 5000:5000
    restart: unless-stopped
    image: mrlt8/wyze-bridge:2.10.3
    environment:
      - WB_AUTH=True
      - WB_USERNAME={{ wyze_bridge_username }}
      - WB_PASSWORD={{ wyze_bridge_password }}
      - ROTATE_DOOR=True
