services:
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:2.10.3
    environment:
      - WB_AUTH=True
      - WB_USERNAME={{ wyze_bridge_username }}
      - WB_PASSWORD={{ wyze_bridge_password }}
      - ROTATE_DOOR=True
  traefik:
    image: traefik:v3.3.3
    container_name: traefik-wyze-bridge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/data/traefik.yaml:/traefik.yaml:ro
      - ./traefik/data/dynamic.yaml:/dynamic.yaml:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock