services:
  umami:
    image: ghcr.io/umami-software/umami:3.3.0@sha256:87312d334d009ee67ee0d2fba8fed01435547cc468e452243aef5133a9984d48
    container_name: umami
    networks:
      - umami
    environment:
      DATABASE_URL: postgresql://{{ umami_db_user}}:{{ umami_db_password }}@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: "{{ umami_app_secret }}"
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: docker.io/postgres:18.4@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    container_name: umami-db
    networks:
      - umami
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: "{{ umami_db_user }}"
      POSTGRES_PASSWORD: "{{ umami_db_password }}"
    volumes:
      - umami-db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  newt:
    image: docker.io/fosrl/newt:1.16.0@sha256:345fdeb369be6608d82c41d70637636c78b2c04a6112ff6ec20fc21c48afc899
    container_name: newt-umami
    restart: unless-stopped
    networks:
      - umami
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ umami_newt_id }}
      - NEWT_SECRET={{ umami_newt_secret }}
volumes:
  umami-db-data:
networks:
  umami:
    name: umami
