services:
  umami:
    image: ghcr.io/umami-software/umami:3.4.0@sha256:85909afc45bdcda1917394594a087421fdbb05610fded0fa9f6fb861abb2f367
    container_name: umami
    networks:
      - umami
    environment:
      DATABASE_URL: postgresql://{{ umami_db_user}}:{{ umami_db_password }}@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: "{{ umami_app_secret }}"
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: docker.io/postgres:18.6@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    container_name: umami-db
    networks:
      - umami
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: "{{ umami_db_user }}"
      POSTGRES_PASSWORD: "{{ umami_db_password }}"
    volumes:
      - umami-db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  newt:
    image: docker.io/fosrl/newt:1.17.0@sha256:3465d85200cceb0f46dad8e63a40b69ec043a81df66ed0c514714302e9b83dde
    container_name: newt-umami
    restart: unless-stopped
    networks:
      - umami
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ umami_newt_id }}
      - NEWT_SECRET={{ umami_newt_secret }}
volumes:
  umami-db-data:
networks:
  umami:
    name: umami
