services:
  umami:
    image: ghcr.io/umami-software/umami:3.1.0@sha256:e3f80c0625aad7179b49da27d475357cabb1068b8cacd9a792cfd6966888b123
    container_name: umami
    networks:
      - umami
    environment:
      DATABASE_URL: postgresql://{{ umami_db_user}}:{{ umami_db_password }}@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: {{ umami_app_secret }}
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: docker.io/postgres:18.3@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    container_name: umami-db
    networks:
      - umami
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: {{ umami_db_user }}
      POSTGRES_PASSWORD: {{ umami_db_password }}
    volumes:
      - umami-db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  newt:
    image: docker.io/fosrl/newt:1.12.3@sha256:414e1a7618cadba03aace19abe2fd5feaa1d7922b95d359d6c1e8329d3fa964c
    container_name: newt-umami
    restart: unless-stopped
    networks:
      - umami
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ umami_newt_id }}
      - NEWT_SECRET={{ umami_newt_secret }}
volumes:
  umami-db-data:
networks:
  umami:
    name: umami
