services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=speedtest-db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME={{ speedtest_tracker_db_username }}
      - DB_PASSWORD={{ speedtest_tracker_db_password }}
      - APP_KEY={{ speedtest_tracker_app_key }}
      - SPEEDTEST_SCHEDULE="*/60 * * * *"
    volumes:
      - ./speedtest-app:/config
      - "./web:/etc/ssl/web"
    image: docker.io/linuxserver/speedtest-tracker:1.15.0@sha256:1193562c4ab4fe29cffd5e6ad4c042a2ed02e218999bedc7c801c96e032d9f9b
    restart: always
    depends_on:
      - speedtest-db
  speedtest-db:
    container_name: speedtest-db
    image: docker.io/postgres:18.4@sha256:a02db8cac496f15b094798a38254f14d6e00741f709360e5e00bb6668ea31636
    restart: always
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER={{ speedtest_tracker_db_username }}
      - POSTGRES_PASSWORD={{ speedtest_tracker_db_password }}
    volumes:
      - ./speedtest-db:/var/lib/postgresql
  apprise:
    image: docker.io/caronc/apprise:v1.5.3@sha256:6a9f18155b8ae6ae3439d4139e17946d3e0afe27340213c1dcf15f730c42a394
    container_name: apprise
    ports:
      - "8000:8000"
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: "1"
    volumes:
      - ./apprise-config:/config
      - ./plugin:/plugin
      - ./attach:/attach
