
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=speedtest-db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME={{ speedtest_tracker_db_username }}
      - DB_PASSWORD={{ speedtest_tracker_db_password }}
      - APP_KEY={{ speedtest_tracker_app_key }}
      - SPEEDTEST_SCHEDULE="*/60 * * * *"
    volumes:
      - ./speedtest-app:/config
      - "./web:/etc/ssl/web"
    image: docker.io/linuxserver/speedtest-tracker:1.14.1@sha256:a2f4b798445ad702df27b028f190cd7247627d1d3c6cb473f684e2738658021f
    restart: always
    depends_on:
      - speedtest-db
  speedtest-db:
    container_name: speedtest-db
    image: docker.io/postgres:18.3@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
    restart: always
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER={{ speedtest_tracker_db_username }}
      - POSTGRES_PASSWORD={{ speedtest_tracker_db_password }}
    volumes:
      - ./speedtest-db:/var/lib/postgresql
  apprise:
    image: docker.io/caronc/apprise:v1.4.1@sha256:25e0577915c2f06233ae1dce077f05c0fc9ba4f0ea89de5aee18a32b2ee9a75c
    container_name: apprise
    ports:
      - "8000:8000"
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: "1"
    volumes:
      - ./apprise-config:/config
      - ./plugin:/plugin
      - ./attach:/attach
