services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=speedtest-db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME={{ speedtest_tracker_db_username }}
      - DB_PASSWORD={{ speedtest_tracker_db_password }}
      - APP_KEY={{ speedtest_tracker_app_key }}
      - SPEEDTEST_SCHEDULE="*/60 * * * *"
    volumes:
      - ./speedtest-app:/config
      - "./web:/etc/ssl/web"
    image: docker.io/linuxserver/speedtest-tracker:1.14.6@sha256:1647a57e0c125eac6c3a5256c499aa8f580fa7d27d0842376277cdf93e137018
    restart: always
    depends_on:
      - speedtest-db
  speedtest-db:
    container_name: speedtest-db
    image: docker.io/postgres:18.4@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    restart: always
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER={{ speedtest_tracker_db_username }}
      - POSTGRES_PASSWORD={{ speedtest_tracker_db_password }}
    volumes:
      - ./speedtest-db:/var/lib/postgresql
  apprise:
    image: docker.io/caronc/apprise:v1.5.1@sha256:1871ed736799f6320d5061b72a60507f62c8747026e830175dc4b9f8adbf78dd
    container_name: apprise
    ports:
      - "8000:8000"
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: "1"
    volumes:
      - ./apprise-config:/config
      - ./plugin:/plugin
      - ./attach:/attach
