services:
  docker-in-docker:
    image: docker.io/docker:29.4.3-dind@sha256:685b91dca8eab7de1dce1c303dbb7a763e4082d6a60db10968adf3295fbd2495
    container_name: "docker_dind"
    privileged: "true"
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    restart: "unless-stopped"
  forgejo:
    image: codeberg.org/forgejo/forgejo:15.0.2@sha256:db04c7114b656f896e206ba3873fe8d3a7adf2daa44907037f0274f4ba653fb9
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__ROOT_URL={{ forgejo_root_url }}
    restart: always
    networks:
      - forgejo
    volumes:
      - ./forgejo:/data
      - /etc/localtime:/etc/localtime:ro
  runner-1:
    image: "data.forgejo.org/forgejo/runner:12@sha256:3d49075f9115054ae2485d8cea2819296a904dfd4f00017285168028615d8533"
    links:
      - docker-in-docker
    depends_on:
      docker-in-docker:
        condition: service_started
    container_name: forgejo-runner-1
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    # User without root privileges, but with access to `./data`.
    user: 1001:1001
    volumes:
      - ./runner1/data:/data
    restart: "unless-stopped"
    command: "forgejo-runner daemon --config runner-config.yml"
  runner-2:
    image: data.forgejo.org/forgejo/runner:12@sha256:3d49075f9115054ae2485d8cea2819296a904dfd4f00017285168028615d8533
    links:
      - docker-in-docker
    container_name: forgejo-runner-2
    depends_on:
      - docker-in-docker
      - forgejo
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    user: 1001:1001
    volumes:
      - ./runner2/data:/data
    restart: "unless-stopped"
    command: "forgejo-runner daemon --config /data/runner-config.yml"
  pangolin:
    image: docker.io/fosrl/newt:1.12.5@sha256:3c009663332145cae39b940b07857469038d5e9d71aacb1497e78795ba4e3b9b
    container_name: pangolin-forgejo
    restart: unless-stopped
    networks:
      - forgejo
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ forgejo_newt_id }}
      - NEWT_SECRET={{ forgejo_newt_secret }}
networks:
  forgejo:
    name: forgejo
