services:
  changedetection:
    image: docker.io/dgtlmoon/changedetection.io:0.55.3@sha256:2d0030e12494be9ebf6a6ebbbad46afe5763f498bbfefe9ebb7f0bf6be3ca5dc
    container_name: changedetection
    ports:
      - 5000:5000
    volumes:
      - ./changedetection:/datastore
    environment:
      - HIDE_REFERER=true
    restart: always
