services:
  changedetection:
    image: docker.io/dgtlmoon/changedetection.io:0.55.7@sha256:736331d2787f94d3201b64aa641e090f67e28577ba505bd7ba5d7c1841e1e0ca
    container_name: changedetection
    ports:
      - 5000:5000
    volumes:
      - ./changedetection:/datastore
    environment:
      - HIDE_REFERER=true
    restart: always
