services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.37.1@sha256:581d68b2a6fc7ebf58d81c878a9f387cbbc0d88ac9d37b298b9cee10168af85b
    container_name: audiobookshelf
    networks:
      - audiobookshelf
    volumes:
      - /mnt/media/Audiobooks:/audiobooks
      - /mnt/media/Podcasts:/podcasts
      - ./metadata:/metadata
      - ./config:/config
    restart: always
  newt:
    image: docker.io/fosrl/newt:1.18.0@sha256:07507a530f3f239bee4dc208aabdd25095df650f132e926245659e1a67aa5de9
    container_name: newt-audiobookshelf
    restart: unless-stopped
    networks:
      - audiobookshelf
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ audiobookshelf_newt_id }}
      - NEWT_SECRET={{ audiobookshelf_newt_secret }}
networks:
  audiobookshelf:
    name: audiobookshelf
