services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.34.0@sha256:4143292c530f6ac6700afd13360c04f477e4f1a81c1c97c4224b1c7e4330c5c4
    container_name: audiobookshelf
    networks:
      - audiobookshelf
    volumes:
      - /mnt/media/Audiobooks:/audiobooks
      - /mnt/media/Podcasts:/podcasts
      - ./metadata:/metadata
      - ./config:/config
    restart: always
  newt:
    image: docker.io/fosrl/newt:1.11.0@sha256:ea9e2bc53850d4a8b2c6019d97172a2b3e3cb1a15412babb4a0f4adc522f4a79
    container_name: newt-audiobookshelf
    restart: unless-stopped
    networks:
      - audiobookshelf
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ audiobookshelf_newt_id }}
      - NEWT_SECRET={{ audiobookshelf_newt_secret }}
networks:
   audiobookshelf:
     name: audiobookshelf
