services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.36.1@sha256:3528a93b6442ffe54bd46771bbbab7c97084e1101071586d9dc2254f30bb4358
    container_name: audiobookshelf
    networks:
      - audiobookshelf
    volumes:
      - /mnt/media/Audiobooks:/audiobooks
      - /mnt/media/Podcasts:/podcasts
      - ./metadata:/metadata
      - ./config:/config
    restart: always
  newt:
    image: docker.io/fosrl/newt:1.17.0@sha256:3465d85200cceb0f46dad8e63a40b69ec043a81df66ed0c514714302e9b83dde
    container_name: newt-audiobookshelf
    restart: unless-stopped
    networks:
      - audiobookshelf
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ audiobookshelf_newt_id }}
      - NEWT_SECRET={{ audiobookshelf_newt_secret }}
networks:
  audiobookshelf:
    name: audiobookshelf
