services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:12.1@sha256:78d3ea1207d1322471fcac39a614f004f2ccf7e878f95ab2977d752f07e4dd7e
    container_name: jellyfin
    user: 1000:1000
    networks:
      - jellyfin
    group_add:
      - "108"
    environment:
      - JELLYFIN_PublishedServerUrl={{ jellyfin_hostname }}
    volumes:
      - ./config:/config
      - /mnt:/mnt:ro
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  newt:
    image: docker.io/fosrl/newt:1.17.0@sha256:3465d85200cceb0f46dad8e63a40b69ec043a81df66ed0c514714302e9b83dde
    container_name: newt-jellyfin
    restart: unless-stopped
    networks:
      - jellyfin
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ jellyfin_newt_id }}
      - NEWT_SECRET={{ jellyfin_newt_secret }}
networks:
  jellyfin:
    name: jellyfin
