services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:12.0@sha256:baba630419915985442f315f08b0cf46d9f4c8a0cc4bd38e94a6d35751dd5ef5
    container_name: jellyfin
    user: 1000:1000
    networks:
      - jellyfin
    group_add:
      - "108"
    environment:
      - JELLYFIN_PublishedServerUrl={{ jellyfin_hostname }}
    volumes:
      - ./config:/config
      - /mnt:/mnt:ro
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  newt:
    image: docker.io/fosrl/newt:1.16.0@sha256:345fdeb369be6608d82c41d70637636c78b2c04a6112ff6ec20fc21c48afc899
    container_name: newt-jellyfin
    restart: unless-stopped
    networks:
      - jellyfin
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ jellyfin_newt_id }}
      - NEWT_SECRET={{ jellyfin_newt_secret }}
networks:
  jellyfin:
    name: jellyfin
