services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:10.11.8@sha256:1694ff069f0c9dafb283c36765175606866769f5d72f2ed56b6a0f1be922fc37
    container_name: jellyfin
    user: 1000:1000
    networks:
      - jellyfin
    group_add:
      - "108"
    environment:
      - JELLYFIN_PublishedServerUrl={{ jellyfin_hostname }}
    volumes:
      - ./config:/config
      - /movies:/movies:ro
      - /tv:/tv:ro
      - /music:/music:ro
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  newt:
    image: docker.io/fosrl/newt:1.12.3@sha256:414e1a7618cadba03aace19abe2fd5feaa1d7922b95d359d6c1e8329d3fa964c
    container_name: newt-jellyfin
    restart: unless-stopped
    networks:
      - jellyfin
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ jellyfin_newt_id }}
      - NEWT_SECRET={{ jellyfin_newt_secret }}
networks:
  jellyfin:
    name: jellyfin
