---
tailnet_caddy_image: "ghcr.io/davegallant/homelab-caddy-cloudflare:2.11.6-a8737d0@sha256:36cb30f2df99d3aa9d41ed3bbf4685e662c9fe42cfbb5b06b4d98173d7473f03"
tailnet_caddy_domain: "{{ inventory_hostname }}.{{ headscale_magic_dns_domain }}"
