services:
  kiwix-serve:
    container_name: kiwix-serve
    image: ghcr.io/kiwix/kiwix-serve:3.8.2@sha256:de4d451d9d9e3e2d37c1a7b5a861698c67cc4c52c364c2a593ba554cddd6ce03
    ports:
      - 8080:8080
    volumes:
      - /mnt/media/kiwix:/data
    command: "*.zim"
