services:
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Toronto
    ports:
      - 5055:5055
    volumes:
      - ./config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
