- name: Install python
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: latest

- name: Install requests
  pip:
    name: requests

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install docker
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: latest

- name: Install loki docker driver
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:3.4.2-amd64
    alias: loki
    state: present

- name: Enable loki docker driver
  community.docker.docker_plugin:
    plugin_name: loki
    state: enable

- name: Write docker daemon json
  ansible.builtin.copy:
    content: |
      {
        "debug" : true,
        "log-driver": "loki",
        "log-opts": {
            "loki-url": "{{ loki_url }}",
            "loki-batch-size": "400",
            "mode": "non-blocking",
            "loki-retries": "2",
            "loki-max-backoff":"800ms",
            "loki-timeout":"1s"
         }
      }
    dest: /etc/docker/daemon.json
    mode: "0644"
