services:
  qbittorrent:
    image: docker.io/linuxserver/qbittorrent:5.2.0@sha256:2e0148428b6769e2ee1eb6781246b6fca4b70cd680edfcb16e7113d9d6cb1631
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=catppuccin-mocha
      - TP_COMMUNITY_THEME=true
    volumes:
      - ~:/config
      - /mnt/media/torrents:/downloads
      - ~/scripts:/scripts
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
