services:
  qbittorrent:
    image: docker.io/linuxserver/qbittorrent:5.2.0@sha256:f76c4363cce0834df43b097682928d217f9f0e0fa1d13781c0934848d543e4ab
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=catppuccin-mocha
      - TP_COMMUNITY_THEME=true
    volumes:
      - ~:/config
      - /mnt/media/torrents:/downloads
      - ~/scripts:/scripts
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
