services:
  qbittorrent:
    image: docker.io/linuxserver/qbittorrent:5.2.0@sha256:eeea9f8a8cdde23555186843d26e8ded1222421f31f98a5cc1b50c2882ebcf4e
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ~:/config
      - /mnt:/mnt
      - ~/scripts:/scripts
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
