services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:2.8.8@sha256:6ef493c8e3bdbaa26c9bfcec330377ae95116fa00660ca0342769063197b1952
    container_name: bentopdf
    restart: always
    networks:
      - bentopdf
  newt:
    image: docker.io/fosrl/newt:1.16.0@sha256:345fdeb369be6608d82c41d70637636c78b2c04a6112ff6ec20fc21c48afc899
    container_name: newt-bentopdf
    restart: unless-stopped
    networks:
      - bentopdf
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ bentopdf_newt_id }}
      - NEWT_SECRET={{ bentopdf_newt_secret }}
networks:
  bentopdf:
    name: bento-pdf
