services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:2.8.5@sha256:2d867aacb8ab5b196d00ee86944b1899d09d72df355384c5e15cf974737963a0
    container_name: bentopdf
    restart: always
    networks:
      - bentopdf
  newt:
    image: docker.io/fosrl/newt:1.12.5@sha256:3c009663332145cae39b940b07857469038d5e9d71aacb1497e78795ba4e3b9b
    container_name: newt-bentopdf
    restart: unless-stopped
    networks:
      - bentopdf
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ bentopdf_newt_id }}
      - NEWT_SECRET={{ bentopdf_newt_secret }}
networks:
   bentopdf:
     name: bento-pdf
