services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:2.8.5@sha256:2d867aacb8ab5b196d00ee86944b1899d09d72df355384c5e15cf974737963a0
    container_name: bentopdf
    restart: always
    networks:
      - bentopdf
  newt:
    image: docker.io/fosrl/newt:1.14.0@sha256:60c78391e3b5cb8a260490fb26b8b7329ed5448077629da89a564af80d3a9fad
    container_name: newt-bentopdf
    restart: unless-stopped
    networks:
      - bentopdf
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ bentopdf_newt_id }}
      - NEWT_SECRET={{ bentopdf_newt_secret }}
networks:
   bentopdf:
     name: bento-pdf
