services:
  suggestarr:
    container_name: suggestarr
    image: lscr.io/linuxserver/suggestarr:5.14.0
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/suggestarr/config:/config
      - /mnt/media/Movies:/mnt/media/Movies
      - /mnt/media/Torrents:/downloads
  traefik:
    image: traefik:v3.1.6
    container_name: traefik-suggestarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/data/traefik.yaml:/traefik.yaml:ro
      - ./traefik/data/dynamic.yaml:/dynamic.yaml:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
