services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:v1.3.8
    container_name: lubelogger
    build: .
    restart: unless-stopped
    volumes:
      - config:/App/config
      - data:/App/data
      - translations:/App/wwwroot/translations
      - documents:/App/wwwroot/documents
      - images:/App/wwwroot/images
      - temp:/App/wwwroot/temp
      - log:/App/log
      - keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 8080:8080
    networks:
      - lubelogger

  traefik:
    image: traefik:v3.1.6
    container_name: traefik-lubelogger
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/data/traefik.yaml:/traefik.yaml:ro
      - ./traefik/data/dynamic.yaml:/dynamic.yaml:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks:
      - lubelogger

volumes:
  config:
  data:
  translations:
  documents:
  images:
  temp:
  log:
  keys:

networks:
  lubelogger:
    name: lubelogger
