---
- name: Install wazuh
  hosts: wazuh
  tasks:
    - ansible.builtin.include_tasks:
        file: ../../tasks/install-docker-on-ubuntu.yml

    - ansible.builtin.include_tasks:
        file: ../../tasks/install-common-dependencies.yml

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: "~/docker-compose.yml"
        mode: "0640"

    - name: Copy traefik data
      ansible.builtin.copy:
        src: ./traefik/
        dest: "~/traefik/"
        mode: "0640"

    - name: Allow https
      community.general.ufw:
        rule: allow
        port: https
        proto: tcp

    - name: Deny ssh
      community.general.ufw:
        rule: deny
        port: ssh
        proto: tcp

    - community.general.ufw:
        rule: allow
        port: "55000" # wazuh api
        proto: tcp

    - community.general.ufw:
        rule: allow
        port: "9200" # wazuh api
        proto: tcp

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
