services:
  vaultwarden:
    image: docker.io/vaultwarden/server:1.35.6@sha256:93072633c6b125628419097fc951d1ce448422a1af1d653805520a8ba90f6956
    ports:
      - 8080:80
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.snake-cloud.ts.net"
    volumes:
      - ./vw-data/:/data/
