services:
  vaultwarden:
    image: docker.io/vaultwarden/server:1.35.7@sha256:9a8eec71f4a52411cc43edc7a50f33e9b6f62b5baca0dd95f0c6e7fd60f1a341
    ports:
      - 8080:80
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.snake-cloud.ts.net"
    volumes:
      - ./vw-data/:/data/
