services:
  vaultwarden:
    image: docker.io/vaultwarden/server:1.35.4@sha256:43498a94b22f9563f2a94b53760ab3e710eefc0d0cac2efda4b12b9eb8690664
    ports:
      - 8080:80
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.snake-cloud.ts.net"
    volumes:
      - ./vw-data/:/data/
