services:
  rfd-fyi:
    image: ghcr.io/davegallant/rfd-fyi:0.4.0@sha256:b908ef9d9c359dd2b291c391bd441012312a33423b71983cf39264cbe2c449c5
    container_name: rfd-fyi
    networks:
      - rfd-fyi
    restart: unless-stopped
  newt:
    image: docker.io/fosrl/newt:1.11.0@sha256:ea9e2bc53850d4a8b2c6019d97172a2b3e3cb1a15412babb4a0f4adc522f4a79
    container_name: newt-rfdfyi
    restart: unless-stopped
    networks:
      - rfd-fyi
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ rfdfyi_newt_id }}
      - NEWT_SECRET={{ rfdfyi_newt_secret }}

networks:
  rfd-fyi:
    name: rfd-fyi
