services:
  rfd-fyi:
    image: ghcr.io/davegallant/rfd-fyi:0.7.0@sha256:452ff75ca03fe27bebbc497435a23c2769286411fd107ec14a94ff52221cea9d
    container_name: rfd-fyi
    networks:
      - rfd-fyi
    restart: unless-stopped
  newt:
    image: docker.io/fosrl/newt:1.12.5@sha256:3c009663332145cae39b940b07857469038d5e9d71aacb1497e78795ba4e3b9b
    container_name: newt-rfdfyi
    restart: unless-stopped
    networks:
      - rfd-fyi
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ rfdfyi_newt_id }}
      - NEWT_SECRET={{ rfdfyi_newt_secret }}

networks:
  rfd-fyi:
    name: rfd-fyi
