services:
  rfd-fyi:
    image: ghcr.io/davegallant/rfd-fyi:0.4.2@sha256:091f89d7f1fdf6d4aa11c0af30ab23d7aebd31a9dc4af31d09e6a2f0a6362c62
    container_name: rfd-fyi
    networks:
      - rfd-fyi
    restart: unless-stopped
  newt:
    image: docker.io/fosrl/newt:1.11.0@sha256:ea9e2bc53850d4a8b2c6019d97172a2b3e3cb1a15412babb4a0f4adc522f4a79
    container_name: newt-rfdfyi
    restart: unless-stopped
    networks:
      - rfd-fyi
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ rfdfyi_newt_id }}
      - NEWT_SECRET={{ rfdfyi_newt_secret }}

networks:
  rfd-fyi:
    name: rfd-fyi
