---
- Stats:
    - Gatus:
        href: "{% raw %}{{HOMEPAGE_VAR_GATUS_URL}}{% endraw %}"
        widget:
          type: gatus
          icon: gatus
          url: "{% raw %}{{HOMEPAGE_VAR_GATUS_URL}}{% endraw %}"
          slug: default
    - Speedtest Tracker:
        href: "{% raw %}{{HOMEPAGE_VAR_SPEEDTEST_TRACKER_URL}}{% endraw %}"
        widget:
          type: speedtest
          icon: speedtest
          url: "{% raw %}{{HOMEPAGE_VAR_SPEEDTEST_TRACKER_URL}}{% endraw %}"
    - gotify:
        icon: gotify
        href: "{% raw %}{{HOMEPAGE_VAR_GOTIFY_URL}}{% endraw %}"
        description: Notifications
        widget:
          type: gotify
          url: "{% raw %}{{HOMEPAGE_VAR_GOTIFY_URL}}{% endraw %}"
          key: "{% raw %}{{HOMEPAGE_VAR_GOTIFY_API_KEY}}{% endraw %}"
    - Immich:
        icon: immich
        href: "{% raw %}{{HOMEPAGE_VAR_IMMICH_URL}}{% endraw %}"
        description: Photo Backup
        widget:
          type: immich
          version: 2
          url: "{% raw %}{{HOMEPAGE_VAR_IMMICH_URL}}{% endraw %}"
          key: "{% raw %}{{HOMEPAGE_VAR_IMMICH_API_KEY}}{% endraw %}"
    - AdGuard Home:
        href: "{% raw %}{{HOMEPAGE_VAR_ADGUARD_HOME_URL}}{% endraw %}"
        icon: adguard-home
        description: DNS
        widget:
          type: adguard
          url: "{% raw %}{{HOMEPAGE_VAR_ADGUARD_HOME_URL}}{% endraw %}"
          username: "{% raw %}{{HOMEPAGE_VAR_ADGUARD_HOME_USERNAME}}{% endraw %}"
          password: "{% raw %}{{HOMEPAGE_VAR_ADGUARD_HOME_PASSWORD}}{% endraw %}"
    - TrueNAS:
        href: "{% raw %}{{HOMEPAGE_VAR_TRUENAS_URL}}{% endraw %}"
        icon: truenas
        description: Network Storage
        widget:
          type: truenas
          url: "{% raw %}{{HOMEPAGE_VAR_TRUENAS_URL}}{% endraw %}"
          version: 2
          key: "{% raw %}{{HOMEPAGE_VAR_TRUENAS_API_KEY}}{% endraw %}"
          enablePools: true
- Quick Links:
    - Proxmox:
        href: "{% raw %}{{HOMEPAGE_VAR_PROXMOX_URL}}{% endraw %}"
        description: Virtualization
        icon: proxmox
    - OPNsense:
        href: "{% raw %}{{HOMEPAGE_VAR_OPNSENSE_URL}}{% endraw %}"
        icon: opnsense
        description: Network Firewall
    - HomeAssistant:
        href: "{% raw %}{{HOMEPAGE_VAR_HOMEASSISTANT_URL}}{% endraw %}"
        description: Home Automation
        icon: home-assistant
    - Jellyfin:
        icon: jellyfin
        href: "{% raw %}{{HOMEPAGE_VAR_JELLYFIN_URL}}{% endraw %}"
        description: Media Server
    - Audiobookshelf:
        icon: audiobookshelf
        href: "{% raw %}{{HOMEPAGE_VAR_AUDIOBOOKSHELF_URL}}{% endraw %}"
        description: Podcast and Audio books
    - Maloja:
        icon: maloja
        href: "{% raw %}{{HOMEPAGE_VAR_MALOJA_URL}}{% endraw %}"
        description: Scrobbles
    - Forgejo:
        icon: forgejo
        href: "{% raw %}{{HOMEPAGE_VAR_FORGEJO_URL}}{% endraw %}"
        description: Git server
    - Navidrome:
        icon: navidrome
        href: "{% raw %}{{HOMEPAGE_VAR_NAVIDROME_URL}}{% endraw %}"
        description: Music
    - Invidious:
        icon: invidious
        href: "{% raw %}{{HOMEPAGE_VAR_INVIDIOUS_URL}}{% endraw %}"
        description: YouTube
    - Changedetection:
        icon: /icons/changedetection.png
        href: "{% raw %}{{HOMEPAGE_VAR_CHANGEDETECTION_URL}}{% endraw %}"
        description: Diff detection
    - BentoPDF:
        icon: bentopdf
        href: "{% raw %}{{HOMEPAGE_VAR_BENTOPDF_URL}}{% endraw %}"
        description: PDF tools
    - Archivebox:
        icon: archivebox
        href: "{% raw %}{{HOMEPAGE_VAR_ARCHIVEBOX_URL}}{% endraw %}"
        description: Website preserver
    - Lubelogger:
        icon: lubelogger
        href: "{% raw %}{{HOMEPAGE_VAR_LUBELOGGER_URL}}{% endraw %}"
        description: Vehicle maintenance tracker
    - Grafana:
        icon: grafana
        href: "{% raw %}{{HOMEPAGE_VAR_GRAFANA_URL}}{% endraw %}"
        description: Visualization
    - WatchYourLAN:
        icon: watchyourlan
        href: "{% raw %}{{HOMEPAGE_VAR_WATCHYOURLAN_URL}}{% endraw %}"
        description: Network IP scanner
    - Beszel:
        icon: beszel
        href: "{% raw %}{{HOMEPAGE_VAR_BESZEL_URL}}{% endraw %}"
        description: Server Monitoring
    - Prowlarr:
        icon: prowlarr
        href: "{% raw %}{{HOMEPAGE_VAR_PROWLARR_URL}}{% endraw %}"
        description: Index manager
    - Umami:
        icon: umami
        href: "{% raw %}{{HOMEPAGE_VAR_UMAMI_URL}}{% endraw %}"
        description: Analytics
    - Romm:
        icon: romm
        href: "{% raw %}{{HOMEPAGE_VAR_ROMM_URL}}{% endraw %}"
        description: Emulation
    - Miniflux:
        href: "{% raw %}{{HOMEPAGE_VAR_MINIFLUX_URL}}{% endraw %}"
        description: RSS
        icon: miniflux
    - Sonarr:
        icon: sonarr.png
        href: "{% raw %}{{HOMEPAGE_VAR_SONARR_URL}}{% endraw %}"
        description: TV
    - Radarr:
        icon: radarr.png
        href: "{% raw %}{{HOMEPAGE_VAR_RADARR_URL}}{% endraw %}"
        description: Movies
    - Lidarr:
        icon: lidarr.png
        href: "{% raw %}{{HOMEPAGE_VAR_LIDARR_URL}}{% endraw %}"
        description: Music
    - Dispatcharr:
        icon: dispatcharr.png
        href: "{% raw %}{{HOMEPAGE_VAR_DISPATCHARR_URL}}{% endraw %}"
        description: TV
    - qBittorrent:
        icon: qbittorrent.png
        href: "{% raw %}{{HOMEPAGE_VAR_QBITTORRENT_URL}}{% endraw %}"
        description: Torrents
    - Seerr:
        icon: seerr
        href: "{% raw %}{{HOMEPAGE_VAR_SEERR_URL}}{% endraw %}"
        description: Media Management
    - paperless-ngx:
        icon: paperless-ngx
        href: "{% raw %}{{HOMEPAGE_VAR_PAPERLESS_NGX_URL}}{% endraw %}"
        description: document management
    - upsnap:
        icon: upsnap
        href: "{% raw %}{{HOMEPAGE_VAR_UPSNAP_URL}}{% endraw %}"
        description: wake on lan
    - GL-MT3000:
        icon: router
        href: "{% raw %}{{HOMEPAGE_VAR_GL_MT3000_URL}}{% endraw %}"
        description: GL.iNet Admin Panel
