set positional-arguments

# Sets up ansible
setup:
	ansible-galaxy collection install -r requirements.yml

# Run ansible-playbook
run argument:
	ansible-playbook playbooks/main.yml -i inventory {{argument}} --vault-password-file .vault_pass
