services:
  navidrome:
    container_name: navidrome
    image: docker.io/deluan/navidrome:0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2
    user: 1000:1000 # should be owner of volumes
    networks:
      - navidrome
    restart: always
    environment:
      - ND_ENABLEINSIGHTSCOLLECTOR=false
      - ND_LASTFM_APIKEY={{ navidrome_lastfm_api_key }}
      - ND_LASTFM_SECRET={{ navidrome_lastfm_api_key }}
      - ND_LISTENBRAINZ_BASEURL=https://maloja.snake-cloud.ts.net/apis/listenbrainz/1/
    volumes:
      - ./data:/data
      - /music:/music:ro
  newt:
    image: docker.io/fosrl/newt:1.11.0@sha256:ea9e2bc53850d4a8b2c6019d97172a2b3e3cb1a15412babb4a0f4adc522f4a79
    container_name: newt-navidrome
    restart: unless-stopped
    networks:
      - navidrome
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ navidrome_newt_id }}
      - NEWT_SECRET={{ navidrome_newt_secret }}
networks:
  navidrome:
    name: navidrome
