services:
  radarr:
    container_name: radarr
    image: docker.io/linuxserver/radarr:6.4.4@sha256:adb6c09d6b729ea5e642c99cea35af72702ef476bf4763f153299ac5db9f0b4f
    ports:
      - 7878:7878
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/radarr/config:/config
      - /mnt:/mnt
