services:
  radarr:
    container_name: radarr
    image: docker.io/linuxserver/radarr:6.1.1@sha256:6f1dda18354ea7f28cead8f6d099fc8222498c3ae165f567d504ed04d70980d7
    ports:
      - 7878:7878
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/radarr/config:/config
      - /mnt/media/Movies:/mnt/media/Movies
      - /mnt/media/Torrents:/downloads
