services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.21.1
    ports:
      - 7878:7878
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/radarr/config:/config
      - /mnt/media/Movies:/mnt/media/Movies
      - /mnt/media/Torrents:/downloads
