services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.14.0
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/radarr/config:/config
      - /mnt/media/Movies:/mnt/media/Movies
      - /mnt/media/Torrents:/downloads
  traefik:
    image: traefik:v3.2.0
    container_name: traefik-radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/data/traefik.yaml:/traefik.yaml:ro
      - ./traefik/data/dynamic.yaml:/dynamic.yaml:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
