services:
  radarr:
    container_name: radarr
    image: docker.io/linuxserver/radarr:6.1.1@sha256:659e5f20500948b1491f31dd85c6f99a43508ce3e46595793e1e15aa955bf6d7
    ports:
      - 7878:7878
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ~/radarr/config:/config
      - /mnt/media/Movies:/mnt/media/Movies
      - /mnt/media/torrents:/downloads
