services:
  beszel:
    image: docker.io/henrygd/beszel:0.18.7@sha256:a849ad80814b6a1a3be665304dcace5d4854b3bed7bde4dd1227e8ce1b82d477
    container_name: beszel
    ports:
      - 8090:8090
    volumes:
      - ${PWD}/beszel-hub/beszel_data:/beszel_data
    restart: always
