
services:
  plex:
    # Tags: https://hub.docker.com/r/linuxserver/plex/tags
    image: linuxserver/plex:1.41.2
    container_name: plex
    # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./config:/config
      - /mnt/media/Movies:/movies:ro
      - "/mnt/media/TV Shows:/tv:ro"
      - "/mnt/media/Music:/music:ro"
    restart: unless-stopped
