services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.27.2@sha256:f2b5ea3128b0513feb07efee7539ad546f3ba3a9095f19936f446f75b8baa894
    container_name: dispatcharr
    restart: always
    networks:
      - dispatcharr
    volumes:
      - dispatcharr_data:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  newt:
    image: docker.io/fosrl/newt:1.15.0@sha256:d69d047c816ca7721eae90d5f3cd3be53b615b3d498678be21488d666538ee5c
    container_name: newt-dispatcharr
    restart: unless-stopped
    networks:
      - dispatcharr
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ dispatcharr_newt_id }}
      - NEWT_SECRET={{ dispatcharr_newt_secret }}
volumes:
  dispatcharr_data:
networks:
  dispatcharr:
    name: dispatcharr
