services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.28.0@sha256:af736a2337830e6a726120a3585d37122be0bca29d5244b7de412c9c34be826a
    container_name: dispatcharr
    restart: always
    networks:
      - dispatcharr
    volumes:
      - dispatcharr_data:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  newt:
    image: docker.io/fosrl/newt:1.15.0@sha256:d69d047c816ca7721eae90d5f3cd3be53b615b3d498678be21488d666538ee5c
    container_name: newt-dispatcharr
    restart: unless-stopped
    networks:
      - dispatcharr
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ dispatcharr_newt_id }}
      - NEWT_SECRET={{ dispatcharr_newt_secret }}
volumes:
  dispatcharr_data:
networks:
  dispatcharr:
    name: dispatcharr
