services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.24.0@sha256:c9920ece0dd653c12ac251aa406351a3006043200f02054472d34c417e365190
    container_name: dispatcharr
    restart: always
    networks:
      - dispatcharr
    volumes:
      - dispatcharr_data:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  newt:
    image: docker.io/fosrl/newt:1.12.5@sha256:3c009663332145cae39b940b07857469038d5e9d71aacb1497e78795ba4e3b9b
    container_name: newt-dispatcharr
    restart: unless-stopped
    networks:
      - dispatcharr
    environment:
      - PANGOLIN_ENDPOINT={{ pangolin_endpoint }}
      - NEWT_ID={{ dispatcharr_newt_id }}
      - NEWT_SECRET={{ dispatcharr_newt_secret }}
volumes:
  dispatcharr_data:
networks:
  dispatcharr:
    name: dispatcharr
